# Gradient Descent 1
Not gate

In [62]:
import numpy as np
import matplotlib.pyplot as plt

In [63]:
x = np.array([[0],[1]])
y = np.array([[1],[0]])
print(x)
print(y)

[[0]
 [1]]
[[1]
 [0]]


In [64]:
def ReLU(x):
    return np.maximum(0, x)

# Derivada de la función ReLU para arrays de numpy
def deriv_ReLU(x):
    return np.where(x >= 0, 1, 0)

def MSE(y, a_2):
    return 0.5 * np.sum((a_2 - y)**2)

In [65]:
# initializa params randomly
w_1 = np.random.rand()
w_2 = np.random.rand()
b_1 = np.random.rand()
b_2 = np.random.rand()

w_1

0.8803857242401402

In [68]:

for i in range(100000):
    # forward propagation

    z_1 = w_1 * x + b_1
    a_1 = ReLU(z_1)
    z_2 = w_2 * a_1 + b_2
    a_2 = ReLU(z_2)
    # gradient_descent

    learning_rate = 0.0001
    delta_2 =(a_2 - y) * deriv_ReLU(z_2)
    
    partial_w2 = delta_2 * a_1
    partial_b2 = delta_2 * 1
    C = MSE(y, a_2)
    w_2 -= partial_w2 * learning_rate
    b_2 -= partial_b2 * learning_rate
    print(C)






0.014526866398215751
0.014521150435161606
0.014515436725735327
0.014509725269047466
0.014504016064208905
0.014498309110330898
0.014492604406525025
0.014486901951903247
0.014481201745577866
0.014475503786661514
0.014469808074267199
0.014464114607508259
0.014458423385498404
0.014452734407351673
0.014447047672182481
0.014441363179105559
0.014435680927236008
0.014430000915689283
0.014424323143581176
0.014418647610027821
0.01441297431414573
0.014407303255051733
0.014401634431863038
0.014395967843697165
0.014390303489672015
0.014384641368905824
0.014378981480517184
0.014373323823625024
0.014367668397348616
0.01436201520080761
0.014356364233121961
0.014350715493412004
0.014345068980798415
0.014339424694402213
0.014333782633344762
0.014328142796747765
0.014322505183733299
0.014316869793423758
0.014311236624941902
0.014305605677410835
0.01429997694995399
0.014294350441695169
0.014288726151758507
0.014283104079268489
0.014277484223349948
0.014271866583128052
0.014266251157728338
0.01426063794627

In [69]:
print(y)
print(a_2)

[[1]
 [0]]
[[9.99999366e-01]
 [4.45098958e-10]]
