# AND GATE

In [7]:
import numpy as np
import matplotlib.pyplot as plt

![waterfall](image.png)

In [8]:
def ReLU(x):
    return np.maximum(0, x)

# Derivada de la función ReLU para arrays de numpy
def deriv_ReLU(x):
    return np.where(x >= 0, 1, 0)

def MSE(y, a_2):
    return 0.5 * np.sum((a_2 - y)**2)

In [9]:
x = np.array([[1,1],[1,0],[0,1],[0,0]]).T
y = np.array([[1],[0],[0],[0]]).T
print(x)
print(y)

[[1 1 0 0]
 [1 0 1 0]]
[[1 0 0 0]]


In [10]:
W1 = np.random.randn(3, 2)
W2 = np.random.randn(1, 3)
b1 = np.random.randn(3,)
b2 = np.random.randn(1,)


![waterfall](backpropagation.png)

In [11]:
learning_rate = 0.001
for i in range(1000):
    # forward propagation
    Z1 = np.dot(W1, x)
    A1 = ReLU(Z1)
    Z2 = np.dot(W2, A1)
    A2 = ReLU(Z2)
    print(y)
    print(Z2)
    print(MSE(y, A2))
    # Backpropagation
    delta2 = (y - A2) * deriv_ReLU(Z2)
    delta1 = np.dot(W2.T, delta2) * deriv_ReLU(Z1)
    W2 -= learning_rate * np.dot(A1, delta2)
    b2 -= learning_rate * delta2
    W1 -= learning_rate * np.dot(x, delta1)
    b1 -= learning_rate * delta1

[[1 0 0 0]]
[[-0.4546402   1.41220598 -0.47647351  0.        ]]
1.497162862834057


ValueError: shapes (3,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)