# AND GATE

In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:
def ReLU(x):
    return np.maximum(0, x)

# Derivada de la función ReLU para arrays de numpy
def deriv_ReLU(x):
    return np.where(x >= 0, 1, 0)

def MSE(y, a_2):
    return 0.5 * np.sum((a_2 - y)**2)

In [37]:
x = np.array([[1,1],[1,0],[0,1],[0,0]]).T
y = np.array([[1],[0],[0],[0]]).T
print(x)
print(y)

[[1 1 0 0]
 [1 0 1 0]]
[[1 0 0 0]]


In [38]:
W1 = np.random.randn(3, 2)
W2 = np.random.randn(1, 3)
b1 = np.random.randn(3,)
b2 = np.random.randn(1,)


In [39]:
# forward propagation
Z1 = np.dot(W1, x)
A1 = ReLU(Z1)
Z2 = np.dot(W2, A1)
A2 = ReLU(Z2)
print(y)
print(Z2)
print(MSE(y, A2))

[[1 0 0 0]]
[[-0.566978   -0.26548279  0.16350296  0.        ]]
0.5133666089924801
